[package]
name = "dada"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[test]]
name = "harness"
harness = false

[dependencies]
dada-lsp = { path = "components/dada-lsp" }
lsp-server = "0.5.2"
lsp-types = "0.83.1"
serde_json = "1.0.72"
serde = "1.0.131"
eyre = "0.6.5"

[dev-dependencies]
walkdir = "2.3.2"
regex = "1.5.4"
similar = "2.1.0"
