[package]
name = "dada"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[test]]
name = "harness"
harness = false

[dependencies]
dada-lang = { path = "components/dada-lang" }
eyre = "0.6.5"
structopt = "0.3"
tracing-subscriber = "0.2"