[book]
authors = ["Niko Matsakis"]
language = "en"
multilingual = false
src = "src"
title = "The Dada Programming Language"

[output.html]
git-repository-url = "https://github.com/dada-lang/dada/tree/main/book"
edit-url-template = "https://github.com/dada-lang/dada/edit/main/book/{path}"